kind: PersistentVolume
apiVersion: v1
metadata:
  name: sostrades-api-data-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
