kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-integration-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  volumeMode: Filesystem
