kind: Secret
apiVersion: v1
metadata:
  name: githuboauth
  namespace: sostrades
data:
  settings.json: >-
    ewogICAgIkdJVEhVQl9DTElFTlRfSUQiOiAiY2ZjOWVjZjc2MmQ2NjhkYWM0MWQiLAogICAgIkdJVEhVQl9DTElFTlRfU0VDUkVUIjogIjk3NzFjMzRiYzAyNzZkNDNlYzIwOWI5ZWM5NDk1ZDNmZTA3NjRhYTQiLAogICAgIkdJVEhVQl9BUElfVVJMIjogImh0dHBzOi8vYXBpLmdpdGh1Yi5jb20vIiwKICAgICJHSVRIVUJfQVVUSF9VUkwiOiAiaHR0cHM6Ly9naXRodWIuY29tL2xvZ2luL29hdXRoLyIKfQ==

type: Opaque
