kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: sostrades
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: mysql-sostrades
    app.kubernetes.io/name: mysql-sostrades
